name: CD Pipeline

on:
  workflow_run: 
    workflows: ["Node.js Docker CI"]
    types: 
      - completed
    branches: ["submission"]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pull Docker image
      run: sudo docker pull geektousif/college-appointment-assignment:latest
        
    - name: Delete Old Container
      run: sudo docker rm -f college-appointment-assignment || true

    - name: Run New Container
      run: sudo docker run -d -p 3000:3000 --name college-appointment-assignment geektousif/college-appointment-assignment:latest
